
- name: "Create Activemq group"
  group:
    name: "{{ amq_group }}"
  become: yes

- name: "Create Activemq user"
  user:
    name: "{{ amq_user }}"
    group: "{{ amq_group }}"
    home: "{{ amq_home_dir }}"
    comment: "ActiveMQ service account"
    createhome: no
    state: present
    system: yes
  become: yes

- name: check to see if tarball already existed
  stat: path="/tmp/apache-activemq-{{ amq_version }}-bin.tar.gz"
  register: tarball_check

- name: "Get tarball - {{ amq_url }}"
  get_url:
    url: "{{ amq_url }}"
    dest: "/tmp/apache-activemq-{{ amq_version }}-bin.tar.gz"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  when: tarball_check.stat.exists == False
  become: yes

- name: Set amq version install dir
  set_fact:
    amq_version_install_dir: "{{ amq_install_dir }}/activemq/{{ amq_version }}"

- name: check to see if tarball successfully downloaded
  stat: path="/tmp/apache-activemq-{{ amq_version }}-bin.tar.gz"
  register: tarball_check

- name: check to see if install dest doesn't exist
  stat: path="{{ amq_version_install_dir }}"
  register: amq_install_dir_check

- name: Create install dir
  file:
    path: "{{ amq_version_install_dir }}"
    state: directory
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    mode: 0775
    recurse: yes
  when: amq_install_dir_check.stat.exists == False
  become: yes

- name: extract activemq {{ amq_version }} from archive
  shell: |
    tar zxf "/tmp/apache-activemq-{{ amq_version }}-bin.tar.gz" --strip-components 1 -C {{ amq_version_install_dir }}
  when: tarball_check.stat.exists == True
  become: yes

- name: create credentials.properties to {{ amq_version_install_dir }}/conf
  template: src=amq_credentials_properties.j2 dest={{ amq_version_install_dir }}/conf/credentials.properties
            owner={{ amq_user }} group={{ amq_group }} mode=0755
  become: yes

